//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecr2
    {
        public int NUMECR { get; set; }
        public string PRENOMECR { get; set; }
        public string NOMECR { get; set; }
        public string PAYSECR { get; set; }
        public string LANGUECR { get; set; }
    }
}
