//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class librairieEntities : DbContext
    {
        public librairieEntities()
            : base("name=librairieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGUE> CATALOGUE { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATION { get; set; }
        public virtual DbSet<DEPOT> DEPOT { get; set; }
        public virtual DbSet<ECRIVAIN> ECRIVAIN { get; set; }
        public virtual DbSet<EDITEUR> EDITEUR { get; set; }
        public virtual DbSet<OUVRAGE> OUVRAGE { get; set; }
        public virtual DbSet<STOCKER> STOCKER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TARIFER> TARIFER { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
        public virtual DbSet<ecr2> ecr2 { get; set; }
        public virtual DbSet<ecr3> ecr3 { get; set; }
        public virtual DbSet<ecr8> ecr8 { get; set; }
        public virtual DbSet<ecr9> ecr9 { get; set; }
        public virtual DbSet<EditeursDeParis> EditeursDeParis { get; set; }
        public virtual DbSet<edParis> edParis { get; set; }
        public virtual DbSet<ParisEditors> ParisEditors { get; set; }
    }
}
